Repository DerpLab/platform_packages_apps_DerpQuest, pull requests merged in 2020-08, with the labels that each got.

#79 DerpQuest: POSP Vol panel styles
  res/values/derpquest_arrays.xml
  res/values/derpquest_strings.xml
  res/xml/derpquest_settings_themes.xml
Labels: enhancement

#80 DerpQuest: Don't translate Volume Panel Values
  res/values/derpquest_strings.xml
Labels: bug

#81 DerpQuest: Update Greek translations
  res/values-el/derpquest_strings.xml
Labels: Translation

#83 DerpQuest: Remove duplicate FOD animations [2/2]
  res/values-el/derpquest_strings.xml
  res/values-fr/derpquest_strings.xml
  res/values-hi/derpquest_strings.xml
  res/values-it/derpquest_strings.xml
  res/values-pl/derpquest_strings.xml
  res/values-pt-rBR/derpquest_strings.xml
  res/values-ru/derpquest_strings.xml
  res/values-vi/derpquest_strings.xml
  res/values-zh-rCN/derpquest_strings.xml
  res/values/derpquest_arrays.xml
  res/values/derpquest_strings.xml
Labels: enhancement
